export const EXISTING_EMAIL = 'EXISTING_EMAIL';
export const JWT_TOKEN_ERROR = 'JWT_TOKEN_ERROR';
export const MISSING_SYSTEM_API_KEY = 'MISSING_SYSTEM_API_KEY';
export const WRONG_SYSTEM_API_KEY = 'WRONG_SYSTEM_API_KEY';
export const MISSING_AUTHORIZATION = 'MISSING_AUTHORIZATION';
export const USER_NOT_EXIST = 'USER_NOT_EXIST';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
