module.exports = {
  development: {
    host: process.env.DB_HOST,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: parseInt(process.env.DB_PORT, 10),
    dialect: 'mysql',
    logging: true,
    logQueryParameters: true,
    migrationStorageTableName: 'sequelize_meta',
  },
  staging: {
    host: process.env.DB_HOST,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: parseInt(process.env.DB_PORT, 10),
    dialect: 'mysql',
    logging: true,
    logQueryParameters: true,
    migrationStorageTableName: 'sequelize_meta',
  },
  production: {
    host: process.env.DB_HOST,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: parseInt(process.env.DB_PORT, 10),
    dialect: 'mysql',
    logging: true,
    logQueryParameters: true,
    migrationStorageTableName: 'sequelize_meta',
  },
};
